[phases.setup]
nixPkgs = ["nodejs_20", "openssl"]

[phases.install]
cmds = ["npm ci"]

[phases.build]
cmds = [
  "DATABASE_URL='postgresql://u:p@localhost:5432/db' npx prisma generate",
  "npm run build"
]

[start]
cmd = "npx prisma migrate deploy && node dist/main"
